### ISSUE TITLE
i18n already #discussion #feature

### ISSUE THREAD

**Issue by mapkyca** [idno/Known#339]
Because there is a wide wide world outside the US. The project should probably look at internationalisation sooner rather than later (sooner makes it easier).
## Things needed/changed
- [x] Timezones (#151)
- [x] Numbers and dates
- [x] setlocale configurable _(addressed by #340)_
- [x] Mechanism for translating strings (maybe something better than elgg's Massive Array Of Strings)
- [ ] Translate those strings (#1002)
- [x] Configurable language header (#818)
- [x] Phase out the date() command (#729)
##

**Comment by benwerd** [comment]
@HongPong I think we're ready to start making this a priority. Transifex looks great: I suspect we'll use a combination of this and gettext on the back-end, so that we can reliably detect the strings we need to run.

**Comment by rikmendes** [comment]
Would be great to have translation soon, the people I'm getting into Known is primarly french speaking
even though I have some Portuguese & Spanish peeps on my list too !

**Comment by pvagner** [comment]
For personal sites this would be fantastic as well. The geeky part of me communicates in english where this is possible, however I don't want to make english notes for my local friends and my family :-)

**Comment by jorge-leon** [comment]
For translating the Known user interface I recommend gettext - but not for content. #1002  mentions that this question is already settled, but is not specific about how.

OpenACS has a cool interface for translating contents. You can switch on a translators view where untranslated content is tagged, you can click on the language (iirc) and you get a form where you can insert/edit the translation.

**Comment by mapkyca** [comment]
Closing. 

Only outstanding issue is Translations, and that has its own ticket (#1002).
